export const projects = [
  {
    key: 0,
    title: "Project Title",
    description: "desc",
    minidesc: "dsfdsfsdg",
    pictures: ["link1", "link2"],
    tech: ["React", "Python", "Html"],
    links: ["link1", "link2"],
  },
  {
    key: 1,
    title: "Project Title 1",
    description: "desc",
    minidesc: "dsfdsfsdg",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 2,
    title: "Project Title 2",
    description: "desc",
    minidesc: "dsfdsfsdgdf",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 3,
    title: "Project Title 3",
    description: "desc",
    minidesc: "dsfdsfsdg erer ert",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "css"],
    links: ["link1", "link2"],
  },
  {
    key: 4,
    title: "Project Title 4",
    description: "desc",
    minidesc: "dsfdsfsdg erer erer",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 5,
    title: "Project Title 5",
    description: "desc",
    minidesc: "dsfdsfsdg erefr erwer ",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
];
