export const projects = [
  {
    key: 0,
    title: "Projet Title",
    description: "desc",
    minidesc: "dsfdsfsdg",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 1,
    title: "Projet Title1",
    description: "desc",
    minidesc: "dsfdsfsdg",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 2,
    title: "Projet Title2",
    description: "desc",
    minidesc: "dsfdsfsdgdf",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 3,
    title: "Projet Title3",
    description: "desc",
    minidesc: "dsfdsfsdg erer ert",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 4,
    title: "Projet Title4",
    description: "desc",
    minidesc: "dsfdsfsdg erer erer",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
  {
    key: 5,
    title: "Projet Title5",
    description: "desc",
    minidesc: "dsfdsfsdg erefr erwer ",
    pictures: ["link1", "link2"],
    tech: ["react", "python", "html"],
    links: ["link1", "link2"],
  },
];
